FROM hgfkeep/ubuntu:base
MAINTAINER hgf 

ENV password=hgfgood
EXPOSE 22

RUN apt update; apt install -y python3 python3-pip
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN pip3 install jupyter
