apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-mysql
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-mysql-deploy
  namespace: default
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-mysql
      env: dev
  template:
    metadata:
      labels:
        app: dev-mysql
        env: dev
    spec:
      containers:
      - name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: hgfgood
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        livenessProbe:
          tcpSocket:
            port: 3306
          timeoutSeconds: 10
          initialDelaySeconds: 30
          successThreshold: 1
          periodSeconds: 10
          failureThreshold: 6
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dev-mysql


---

apiVersion: v1
kind: Service
metadata:
  name: dev-mysql-service
spec:
  type: NodePort
  selector:
    app: dev-mysql
    env: dev
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
