version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./www:/var/www
#      - /etc/letsencrypt:/etc/letsencrypt
