name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOEKN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: awesome-dev/dev/smartide/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smartide:$(curl -L -s https://smartidedl.blob.core.chinacloudapi.cn/releases/stable.txt)
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: awesome-dev/dev/smartide/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smartide:latest
